import { se } from "date-fns/locale";

// Website Development Packages Data (serviceId: 3)
export const websitePackagesData = [
  {
    serviceId: 3,
    type: "Mini Web Company Profile",
    highlight: false,
    price: 1350000,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "1 Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 2x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: false },
      { feature: "CMS Admin", status: false },
      { feature: "Free 1 Professional Email", status: false },
      { feature: "Free 10 Related Article Content", status: false },
      { feature: "Free 5 Design Product", status: false },
      { feature: "Login Owner & User", status: false },
      { feature: "Payment Gateway", status: false },
      { feature: "Client Request Feature", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Company Profile Basic",
    highlight: false,
    price: 3950000,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Up to 8 Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 2x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: false },
      { feature: "CMS Admin", status: false },
      { feature: "Free 1 Professional Email", status: false },
      { feature: "Free 10 Related Article Content", status: false },
      { feature: "Free 5 Design Product", status: false },
      { feature: "Login Owner & User", status: false },
      { feature: "Payment Gateway", status: false },
      { feature: "Client Request Feature", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Blog Static / Product Catalog",
    highlight: false,
    price: 7000000,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Dynamic Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 4x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: true },
      { feature: "1 Internal Admin", status: true },
      { feature: "Client Request Feature", status: true },
      { feature: "CMS Admin", status: false },
      { feature: "Free 1 Professional Email", status: false },
      { feature: "Free 10 Related Article Content", status: false },
      { feature: "Free 5 Design Product", status: false },
      { feature: "Login Owner & User", status: false },
      { feature: "Payment Gateway", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Dynamic Data Company Profile",
    highlight: false,
    price: 14000000,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Up to 15 Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 4x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: true },
      { feature: "CMS Admin", status: true },
      { feature: "Free 1 Professional Email", status: false },
      { feature: "Free 10 Related Article Content", status: false },
      { feature: "Free 5 Design Product", status: false },
      { feature: "Login Owner & User", status: false },
      { feature: "Payment Gateway", status: false },
      { feature: "Client Request Feature", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Company Blog Website",
    highlight: false,
    price: 18000000,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Dynamic Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 4x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: true },
      { feature: "CMS Admin", status: true },
      { feature: "Free 1 Professional Email", status: true },
      { feature: "Free 10 Related Article Content", status: true },
      { feature: "Login Owner Only", status: true },
      { feature: "Payment Gateway", status: false },
      { feature: "Client Request Feature", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Company Business E-Commerce",
    highlight: true,
    price: 33183500,
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Dynamic Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 4x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: true },
      { feature: "CMS Admin", status: true },
      { feature: "Free 1 Professional Email", status: true },
      { feature: "Free 5 Design Product", status: true },
      { feature: "Login Owner & User", status: true },
      { feature: "Payment Gateway", status: true },
      { feature: "Client Request Feature", status: false },
    ],
  },
  {
    serviceId: 3,
    type: "Custom Web Client Request",
    highlight: false,
    price: 0,
    discount: 0,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
    features: [
      { feature: "Dynamic Page", status: true },
      { feature: "Domain Included", status: true },
      { feature: "SEO Friendly", status: true },
      { feature: "Design Premium", status: true },
      { feature: "Design Responsive", status: true },
      { feature: "Lifetime Support & Maintenance Teknis", status: true },
      { feature: "Content Writing", status: true },
      { feature: "SSL Included (Https)", status: true },
      { feature: "Revisi 4x", status: true },
      { feature: "Integrasi Sosial media", status: true },
      { feature: "Managed Server Data", status: true },
      { feature: "CMS Admin", status: true },
      { feature: "Free 1 Professional Email", status: true },
      { feature: "Free Design Or Content", status: true },
      { feature: "Login Owner & User", status: true },
      { feature: "Payment Gateway", status: true },
      { feature: "Client Request Feature", status: true },
    ],
  },
];

// Social Media Management Packages Data (serviceId: 7)
export const socialMediaPackagesData = [
  {
    serviceId: 7,
    type: "Paket BotLane",
    highlight: false,
    price: 1995000, // 2850000 * 0.7
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Social%20Media%20Management%20nih!%20",
    features: [
      { feature: "Free Template Post", status: true },
      { feature: "Design Feed 14", status: true },
      { feature: "Design Story 4", status: true },
      { feature: "Including 4 Content Carousel", status: true },
      { feature: "Free 14 Copy Writing", status: true },
      { feature: "Free Admin Post (with Meta & Scheduling)", status: true },
      { feature: "Free Optimasi Hastag Tertarget Brand & Viral", status: true },
      { feature: "100% Original Design", status: true },
      { feature: "Unlimited Revision", status: true },
      { feature: "1 Reels Content", status: false },
      { feature: "Free Create Homepage Facebook", status: false },
      { feature: "Free Ads Consulting", status: false },
      { feature: "Free 1 Week Ads", status: false },
      { feature: "Free Ads Content", status: false },
      { feature: "Monthly Reporting", status: false },
      { feature: "Raw File Editable", status: false },
    ],
  },
  {
    serviceId: 7,
    type: "Paket Midlane",
    highlight: false,
    price: 5005000, // 7150000 * 0.7
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Social%20Media%20Management%20nih!%20",
    features: [
      { feature: "Free Template Post", status: true },
      { feature: "Design Feed 24", status: true },
      { feature: "Design Story 7", status: true },
      { feature: "Including 6 Content Carousel", status: true },
      { feature: "Free 25 Copy Writing", status: true },
      { feature: "Free Admin Post (with Meta & Scheduling)", status: true },
      { feature: "Free Optimasi Hastag Tertarget Brand & Viral", status: true },
      { feature: "100% Original Design", status: true },
      { feature: "Unlimited Revision", status: true },
      { feature: "1 REEL Content", status: true },
      { feature: "Free Create Homepage Facebook", status: true },
      { feature: "Free Ads Consulting", status: true },
      { feature: "Free 1 Week Ads", status: false },
      { feature: "Free Ads Content", status: false },
      { feature: "Monthly Reporting", status: false },
      { feature: "Raw File Editable", status: false },
    ],
  },
  {
    serviceId: 7,
    type: "Paket Jungler",
    highlight: true,
    price: 10010000, // 14300000 * 0.7
    discount: 30,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Social%20Media%20Management%20nih!%20",
    features: [
      { feature: "Free Template Post", status: true },
      { feature: "Design Feed 30", status: true },
      { feature: "Design Story 10", status: true },
      { feature: "Including 8 Content Carousel", status: true },
      { feature: "Free 33 Copy Writing", status: true },
      { feature: "Free Admin Post (with Meta & Scheduling)", status: true },
      { feature: "Free Optimasi Hastag Tertarget Brand & Viral", status: true },
      { feature: "100% Original Design", status: true },
      { feature: "Unlimited Revision", status: true },
      { feature: "3 REEL's Content", status: true },
      { feature: "Free Create Homepage Facebook", status: true },
      { feature: "Free Ads Consulting", status: true },
      { feature: "Free 1 Week Ads", status: true },
      { feature: "Free Ads Content", status: true },
      { feature: "Monthly Reporting", status: true },
      { feature: "Raw File Editable", status: true },
    ],
  },
];


//------------------------------------------------------------------
// BELUM DI ADJUST FORMATNYA - samain kayak diatas format key nya
//------------------------------------------------------------------

// serviceId : 1
export const PTPackagesRaw = [
    {
        type: "PT DASAR",
        highlight: true,
        price: 4500000,
        priceOriginal: 8550000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PT LENGKAP",
        highlight: true,
        price: 5000000,
        priceOriginal: 9500000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PT LENGKAP + PKP",
        highlight: false,
        price: 6000000,
        priceOriginal: 11400000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Sertifikat Elektronik", status: true },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PT LENGKAP + WEBSITE COMPANY",
        highlight: true,
        price: 6500000,
        priceOriginal: 10205000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PT LENGKAP + PKP + WEBSITE COMPANY",
        highlight: false,
        price: 7000000,
        priceOriginal: 10990000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Sertifikat Elektronik", status: true }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PAKET SILVER PT PERORANGAN",
        highlight: false,
        price: 600000,
        priceOriginal: 942000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama PT Perorangan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "Surat Pernyataan Kemenkumham", status: true },
            { feature: "NPWP PT Perorangan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak PT (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email PT Perorangan", status: true },
            { feature: "Free Stempel PT Perorangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak (SPPKP)", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false }
        ]
    },
    {
        sourcePage: "pendirian-pt",
        keywords: [],
        type: "PAKET GOLD PT PERORANGAN",
        highlight: false,
        price: 1500000,
        priceOriginal: 2350000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama PT Perorangan", status: true },
            { feature: "Akta Penegasan Pendirian", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "Surat Pernyataan Kemenkumham", status: true },
            { feature: "NPWP PT Perorangan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak PT (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email PT Perorangan", status: true },
            { feature: "Free Stempel PT Perorangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak (SPPKP)", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false }
        ]
    }
];

// serviceId : 2
export const CVPackagesRaw = [
    {
        type: "CV Dasar",
        highlight:true,
        price: 3000000,
        priceOriginal: 4710000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profil", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Website Company", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap",
        highlight:true,
        price: 3500000,
        priceOriginal: 5495000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap + PKP",
        highlight:false,
        price: 4500000,
        priceOriginal: 7065000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Serifikat Elektronik", status: true },
            { feature: "Website Company", status: false }
        ]
    },
    {
        type: "CV Lengkap + Website Company",
        highlight:true,
        price: 5000000,
        priceOriginal: 7800000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap + PKP + Website",
        highlight:false,
        price: 6000000,
        priceOriginal: 9420000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Serifikat Elektronik", status: true }
        ]
    }
];

// serviceId : 10
export const VirtualOfficePackagesRaw = [
    {
        type: "VIRTUAL OFFICE",
        price: 2650000,
        priceOriginal: 3948500,
        discount: 30,
        duration: "1 Tahun",
        features: [
            { feature: "Perjanjian Sewa Menyewa 1 Tahun", status: true },
            { feature: "Sudah Termasuk PPN dan PPH", status: true },
            { feature: "Alamat Virtual Office Bisa PKP", status: true },
            { feature: "Bisa Pakai Ruang Meeting diseluruh Cabang Virtual Office", status: true },
            { feature: "Layanan Surat Menyurat", status: true },
            { feature: "Notifikasi Atas Dokumen Atau Surat Masuk", status: true },
            { feature: "Free Surat Domisili Gedung", status: true },
            { feature: "Free Wifi", status: true },
            { feature: "Self Service Pantry", status: true },
            { feature: "Alamat Komersil dan Prestisius", status: true },
            { feature: "Bonus Meeting Room Gratis 60-90 Jam Pertahun", status: true },
            { feature: "Fasilitas Live Streaming", status: true },
            { feature: "Fasilitas Podcast", status: true },
            { feature: "Fasilitas Proyektor", status: true }
        ]
    },
    {
        type: "VIRTUAL OFFICE PREMIUM (SCBD)",
        price: 3999000,
        priceOriginal: 5718570,
        discount: 30,
        duration: "1 Tahun",
        features: [
            { feature: "Perjanjian Sewa Menyewa 1 Tahun", status: true },
            { feature: "Sudah Termasuk PPN dan PPH", status: true },
            { feature: "Alamat Virtual Office Bisa PKP", status: true },
            { feature: "Bisa Pakai Ruang Meeting diseluruh Cabang Virtual Office", status: true },
            { feature: "Layanan Surat Menyurat", status: true },
            { feature: "Notifikasi Atas Dokumen Atau Surat Masuk", status: true },
            { feature: "Free Surat Domisili Gedung", status: true },
            { feature: "Free Wifi", status: true },
            { feature: "Self Service Pantry", status: true },
            { feature: "Alamat Komersil dan Prestisius", status: true },
            { feature: "Bonus Meeting Room Gratis 60-90 Jam Pertahun", status: true },
            { feature: "Fasilitas Live Streaming", status: true },
            { feature: "Fasilitas Podcast", status: true },
            { feature: "Fasilitas Proyektor", status: true }
        ]
    }
];

// serviceId : 8
export const KonsultanPajakPackagesRaw = [
  {
    type: "Pelaporan SPT Masa Tahunan Pribadi (Non Pegawai Nihil) 1 Tahun",
    price: 100000,
    priceOriginal: 156250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Pelaporan%20SPT%20Masa%20Tahunan%20Pribadi%20(Non%20Pegawai%20Nihil)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Pelaporan SPT Masa Tahunan Pribadi (Non Pegawai Omzet) 1 Tahun",
    price: 200000,
    priceOriginal: 312500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Pelaporan%20SPT%20Masa%20Tahunan%20Pribadi%20(Non%20Pegawai%20Omzet)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Pelaporan SPT Masa Tahunan Pribadi (Pegawai) 1 Tahun",
    price: 100000,
    priceOriginal: 156250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Pelaporan%20SPT%20Masa%20Tahunan%20Pribadi%20(Pegawai)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Pelaporan SPT Masa Tahunan Badan Usaha (Nihil) 1 Tahun",
    price: 500000,
    priceOriginal: 781250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Pelaporan%20SPT%20Masa%20Tahunan%20Badan%20Usaha%20(Nihil)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Laporan keuangan", status: true },
      { feature: "Review Laporan Keuangan", status: true },
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
      { feature: "SPT Masa Tahunan Badan", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan SPT PPh 21 Pegawai",
      "Laporan PPh 23",
      "Laporan PPh Final",
      "Laporan PPN (Jika Sudah PKP)",
      "Laporan SPT PPh 25/29",
      "Pajak Daerah (Jika Ada)",
      "Perencanaan Pajak",
    ],
  },
  {
    type: "Pelaporan SPT Masa Tahunan Badan Usaha (Omzet) 1 Tahun",
    price: 1000000,
    priceOriginal: 1562500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Pelaporan%20SPT%20Masa%20Tahunan%20Badan%20Usaha%20(Omzet)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Laporan keuangan", status: true },
      { feature: "Review Laporan Keuangan", status: true },
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
      { feature: "SPT Masa Tahunan Badan", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Laporan Keuangan (Jika Ada)",
      "SPT PPh 21 Pegawai (Jika Ada)",
      "SPT PPN (Jika PKP)",
      "Bukti Potong PPh (Jika Ada)",
      "Akta Perusahaan Pendirian s/d Perubahan Terakhir",
      "KTP & NPWP Direksi",
      "NPWP Perusahaan",
    ],
  },
  {
    type: "Konsultan Pajak Badan PMDN (Kontrak 1 Tahun) Omzet Kurang dari 5M",
    price: 1000000,
    priceOriginal: 1562500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Badan%20PMDN%20(Kontrak%201%20Tahun)%20Omzet%20Kurang%20dari%205M!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT PPh 21 Pegawai", status: true },
      { feature: "Laporan PPh 23", status: true },
      { feature: "Laporan PPh Final", status: true },
      { feature: "Laporan PPN (Jika Sudah PKP)", status: true },
      { feature: "Laporan SPT PPh 25/29", status: true },
      { feature: "Pajak Daerah (Jika Ada)", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Akun PKP (Jika Sudah PKP)",
      "Rekap Pengeluaran",
      "Rekap Pemasukan",
      "Mutasi Rekening Bank",
      "AP (Account Payable)",
      "AR (Account Receivable)",
      "Daftar Asset Perusahaan",
      "Daftar Gaji Karyawan",
    ],
  },
  {
    type: "Konsultan Pajak Badan PMDN (Kontrak 1 Tahun) Omzet 5M s/d 15M",
    price: 1500000,
    priceOriginal: 2343750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Badan%20PMDN%20(Kontrak%201%20Tahun)%20Omzet%205M%20s/d%2015M!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT PPh 21 Pegawai", status: true },
      { feature: "Laporan PPh 23", status: true },
      { feature: "Laporan PPh Final", status: true },
      { feature: "Laporan PPN (Jika Sudah PKP)", status: true },
      { feature: "Laporan SPT PPh 25/29", status: true },
      { feature: "Pajak Daerah (Jika Ada)", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Akun PKP (Jika Sudah PKP)",
      "Rekap Pengeluaran",
      "Rekap Pemasukan",
      "Mutasi Rekening Bank",
      "AP (Account Payable)",
      "AR (Account Receivable)",
      "Daftar Asset Perusahaan",
      "Daftar Gaji Karyawan",
    ],
  },
  {
    type: "Konsultan Pajak Badan PMDN (Kontrak 1 Tahun) Omzet 15M s/d 50M",
    price: 2500000,
    priceOriginal: 3906250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Badan%20PMDN%20(Kontrak%201%20Tahun)%20Omzet%2015M%20s/d%2050M!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT PPh 21 Pegawai", status: true },
      { feature: "Laporan PPh 23", status: true },
      { feature: "Laporan PPh Final", status: true },
      { feature: "Laporan PPN (Jika Sudah PKP)", status: true },
      { feature: "Laporan SPT PPh 25/29", status: true },
      { feature: "Pajak Daerah (Jika Ada)", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Akun PKP (Jika Sudah PKP)",
      "Rekap Pengeluaran",
      "Rekap Pemasukan",
      "Mutasi Rekening Bank",
      "AP (Account Payable)",
      "AR (Account Receivable)",
      "Daftar Asset Perusahaan",
      "Daftar Gaji Karyawan",
    ],
  },
  {
    type: "Konsultan Pajak Badan PMDN (Kontrak 1 Tahun) Omzet Lebih dari 50M",
    price: 5000000,
    priceOriginal: 7812500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Badan%20PMDN%20(Kontrak%201%20Tahun)%20Omzet%20Lebih%20dari%2050M!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT PPh 21 Pegawai", status: true },
      { feature: "Laporan PPh 23", status: true },
      { feature: "Laporan PPh Final", status: true },
      { feature: "Laporan PPN (Jika Sudah PKP)", status: true },
      { feature: "Laporan SPT PPh 25/29", status: true },
      { feature: "Pajak Daerah (Jika Ada)", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Akun PKP (Jika Sudah PKP)",
      "Rekap Pengeluaran",
      "Rekap Pemasukan",
      "Mutasi Rekening Bank",
      "AP (Account Payable)",
      "AR (Account Receivable)",
      "Daftar Asset Perusahaan",
      "Daftar Gaji Karyawan",
    ],
  },
  {
    type: "Konsultan Pajak Pribadi (Non Pegawai Nihil) 1 Tahun",
    price: 500000,
    priceOriginal: 781250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Pribadi%20(Non%20Pegawai%20Nihil)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Konsultan Pajak Pribadi (Non Pegawai Omzet) 1 Tahun",
    price: 750000,
    priceOriginal: 1171875,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Pribadi%20(Non%20Pegawai%20Omzet)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Konsultan Pajak Pribadi (Pegawai) 1 Tahun",
    price: 500000,
    priceOriginal: 781250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultan%20Pajak%20Pribadi%20(Pegawai)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Perencanaan Pajak", status: true },
      { feature: "Bukti Pelaporan Elektronik", status: true },
    ],
    requirements: [
      "Akun DJP Online",
      "Bukti Potong",
      "Kartu Keluarga",
      "KTP",
      "Asset",
    ],
  },
  {
    type: "Penyusunan Laporan Keuangan UMKM (Sederhana) 1 Tahun",
    price: 300000,
    priceOriginal: 468750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Laporan%20Keuangan%20UMKM%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
    ],
    requirements: [
      "Rekonsiliasi Bank",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Jurnal Keuangan",
    ],
  },
  {
    type: "Penyusunan Laporan Keuangan UMKM (Kompleks) 1 Tahun",
    price: 600000,
    priceOriginal: 937500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Laporan%20Keuangan%20UMKM%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT", status: true },
    ],
    requirements: [
      "Rekonsiliasi Bank",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Jurnal Keuangan",
      "Laporan SPT",
    ],
  },
  {
    type: "Penyusunan Laporan Keuangan Badan (Sederhana) 1 Tahun",
    price: 800000,
    priceOriginal: 1250000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Laporan%20Keuangan%20Badan%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan Pajak", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan Pajak",
    ],
  },
  {
    type: "Penyusunan Laporan Keuangan Badan (Kompleks) 1 Tahun",
    price: 1500000,
    priceOriginal: 2343750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Laporan%20Keuangan%20Badan%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan Pajak", status: true },
      { feature: "Laporan SPT", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan Pajak",
      "Laporan SPT",
    ],
  },
  {
    type: "Konsultasi Pajak UMKM (Sederhana) 1 Tahun",
    price: 500000,
    priceOriginal: 781250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultasi%20Pajak%20UMKM%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
    ],
  },
  {
    type: "Konsultasi Pajak UMKM (Kompleks) 1 Tahun",
    price: 1000000,
    priceOriginal: 1562500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultasi%20Pajak%20UMKM%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan SPT", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan SPT",
    ],
  },
  {
    type: "Konsultasi Pajak Badan (Sederhana) 1 Tahun",
    price: 1000000,
    priceOriginal: 1562500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultasi%20Pajak%20Badan%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan Pajak", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan Pajak",
    ],
  },
  {
    type: "Konsultasi Pajak Badan (Kompleks) 1 Tahun",
    price: 2000000,
    priceOriginal: 3125000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Konsultasi%20Pajak%20Badan%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Jurnal Keuangan", status: true },
      { feature: "Laporan Neraca", status: true },
      { feature: "Laporan Laba / Rugi", status: true },
      { feature: "Rekonsiliasi Bank", status: true },
      { feature: "Laporan Pajak", status: true },
      { feature: "Laporan SPT", status: true },
    ],
    requirements: [
      "Jurnal Keuangan",
      "Laporan Neraca",
      "Laporan Laba / Rugi",
      "Rekonsiliasi Bank",
      "Laporan Pajak",
      "Laporan SPT",
    ],
  },
  {
    type: "Penyusunan Anggaran Keuangan UMKM (Sederhana) 1 Tahun",
    price: 400000,
    priceOriginal: 625000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Anggaran%20Keuangan%20UMKM%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Penyusunan Anggaran", status: true },
      { feature: "Analisis Anggaran", status: true },
    ],
    requirements: [
      "Data Keuangan Tahun Lalu",
      "Proyeksi Pendapatan",
      "Proyeksi Pengeluaran",
    ],
  },
  {
    type: "Penyusunan Anggaran Keuangan UMKM (Kompleks) 1 Tahun",
    price: 800000,
    priceOriginal: 1250000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Anggaran%20Keuangan%20UMKM%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Penyusunan Anggaran", status: true },
      { feature: "Analisis Anggaran", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Data Keuangan Tahun Lalu",
      "Proyeksi Pendapatan",
      "Proyeksi Pengeluaran",
      "Proyeksi Pajak",
    ],
  },
  {
    type: "Penyusunan Anggaran Keuangan Badan (Sederhana) 1 Tahun",
    price: 600000,
    priceOriginal: 937500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Anggaran%20Keuangan%20Badan%20(Sederhana)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Penyusunan Anggaran", status: true },
      { feature: "Analisis Anggaran", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Data Keuangan Tahun Lalu",
      "Proyeksi Pendapatan",
      "Proyeksi Pengeluaran",
      "Proyeksi Pajak",
    ],
  },
  {
    type: "Penyusunan Anggaran Keuangan Badan (Kompleks) 1 Tahun",
    price: 1200000,
    priceOriginal: 1875000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Penyusunan%20Anggaran%20Keuangan%20Badan%20(Kompleks)%201%20Tahun!",
    discount: 36,
    features: [
      { feature: "Penyusunan Anggaran", status: true },
      { feature: "Analisis Anggaran", status: true },
      { feature: "Perencanaan Pajak", status: true },
    ],
    requirements: [
      "Data Keuangan Tahun Lalu",
      "Proyeksi Pendapatan",
      "Proyeksi Pengeluaran",
      "Proyeksi Pajak",
    ],
  },
];

// serviceId : 4
export const BadanUsahaPackagesRaw = [
    {
        type: "Pendirian Yayasan",
        price: 4000000,
        priceOriginal: 6820000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Yayasan%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Yayasan", status: true },
            { feature: "Akta Pendirian Yayasan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Yayasan", status: true },
            { feature: "Free Stempel Nama Yayasan", status: true }
        ]
    },
    {
        type: "Pendirian Perkumpulan/Asosiasi",
        price: 4000000,
        priceOriginal: 6820000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Asosiasi/Perkumpulan%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Perkumpulan", status: true },
            { feature: "Akta Pendirian Yayasan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Perkumpulan", status: true },
            { feature: "Free Stempel Nama Perkumpulan", status: true }
        ]
    },
    {
        type: "Pendirian Firma Hukum",
        price: 3000000,
        priceOriginal: 4710000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Firma%20Hukum%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Firma Hukum", status: true },
            { feature: "Akta Pendirian Perkumpulan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Firma Hukum", status: true },
            { feature: "Free Stempel Firma Hukum", status: true }
        ]
    },
];

// serviceId : 5
export const HakiPackagesRaw = [
    {
        type: "Pengurusan HAKI (Merek, Hak Cipta, Paten, dll.)",
        price: 3800000,
        priceOriginal: 5937500,
        link: "https://api.whatsapp.com/send?phone=628887127000",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Proses 1-2 Hari Kerja", status: true }
        ]
    }
];

// serviceId : 11
export const goSpace = [
  {
    title: "Virtual Office Space Lite",
    benefit: [
      "Alamat Domisili Prestisius",
      "Resepsionis Profesional",
      "Penerimaan Surat & Paket",
      "Free Wifi",
      "Akses Private Lift",
      "Smart TV",
      "Whiteboard",
      "Free Tea & Coffee",
      "Self Service Pantry",
      "Free meeting room 40 jam/tahun",
      "Ruang meeting besar (10 orang)",
      "Ruang meeting kecil (5 orang)",
      "Meeting room smoking area (3 orang)",
    ],
    originalPrice: "Rp 2.550.000",
    price: "Rp 1.700.000",
    discount: "33% OFF",
    // period: "/ bulan",
    description:
      "Solusi virtual office dengan fasilitas lengkap untuk profesional dan bisnis kecil yang membutuhkan alamat prestisius dan meeting room.",
    img: "/images/go-space-assets/spaces/room-4-1.jpg",
    popular: true,
  },
  {
    title: "Virtual Office Space Core",
    benefit: [
      "Alamat Domisili Prestisius",
      "Resepsionis Profesional",
      "Penerimaan Surat & Paket",
      "Free Wifi",
      "Akses Private Lift",
      "Smart TV",
      "Whiteboard",
      "Free Tea & Coffee",
      "Self Service Pantry",
      "Free meeting room 90 jam/tahun",
      "Ruang meeting besar (10 orang)",
      "Ruang meeting kecil (5 orang)",
      "Meeting room smoking area (3 orang)",
    ],
    originalPrice: "Rp 3.750.000",
    price: "Rp 2.500.000",
    discount: "33% OFF",
    // period: "/ bulan",
    description:
      "Paket virtual office premium dengan jam meeting room yang lebih banyak untuk bisnis yang memerlukan fleksibilitas lebih tinggi.",
    img: "/images/go-space-assets/spaces/room-12-1.jpg",
    popular: true,
  },
];

// serviceId : 9
export const AccountantPackagesRaw = [
    {
        type: "Jasa Akuntansi (Kontrak) Omzet Kurang dari 2,5 M (1 Tahun)",
        price: 800000,
        priceOriginal: 1250000, // price = priceOriginal * (1 - discount)
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%20Kurang%20dari%202,5%20M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 2,5M s/d 5M (1 Tahun)",
        price: 1300000,
        priceOriginal: 2031250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%202,5M%20s/d%205M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 5M s/d 7,5M (1 Tahun)",
        price: 1800000,
        priceOriginal: 2812500,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%205M%20s/d%207,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 7,5M s/d 10M (1 Tahun)",
        price: 2300000,
        priceOriginal: 3593750,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%207,5M%20s/d%2010M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 10M s/d 12,5M (1 Tahun)",
        price: 2800000,
        priceOriginal: 4375000,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2010M%20s/d%2012,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 12,5M s/d 15M (1 Tahun)",
        price: 3300000,
        priceOriginal: 5156250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2012,5M%20s/d%2015M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 15M s/d 17,5M (1 Tahun)",
        price: 3800000,
        priceOriginal: 5937500,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2015M%20s/d%2017,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 17,5M s/d 20M (1 Tahun)",
        price: 4300000,
        priceOriginal: 6718750,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2017,5M%20s/d%2020M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 20M s/d 25M (1 Tahun)",
        price: 4800000,
        priceOriginal: 7500000,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2020M%20s/d%2025M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 25M s/d 30M (1 Tahun)",
        price: 5300000,
        priceOriginal: 8281250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2025M%20s/d%2030M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
];

// serviceId : 6
export const servicePackagesRaw = [
  {
    type: "Pengurusan Izin SKPL A",
    price: 3500000,
    priceOriginal: 5468750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20pengurusan%20Izin%20SKPL%20A!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Standar SKPL - A", status: true }
    ]
  },
  {
    type: "Pengurusan SBUJK Skala Kecil",
    price: 9000000,
    priceOriginal: 14062500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20pengurusan%20SBUJK%20Skala%20Kecil!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Badan Usaha Jasa Konstruksi (SBJUK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "Pengurusan SBUJK Skala Menengah",
    price: 11000000,
    priceOriginal: 17187500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20pengurusan%20SBUJK%20Skala%20Menengah!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Badan Usaha Jasa Konstruksi (SBJUK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "Pengurusan SBUJK Skala Besar",
    price: 15000000,
    priceOriginal: 23437500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20pengurusan%20SBUJK%20Skala%20Besar!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Badan Usaha Jasa Konstruksi (SBJUK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "Sertifikat Kompetensi Kerja (SKK) Jenjang 4-6",
    price: 3500000,
    priceOriginal: 5468750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Sertifikat%20Kompetensi%20Kerja%20(SKK)%20Jenjang%204-6!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Kompetensi Kerja (SKK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "Sertifikat Kompetensi Kerja (SKK) Jenjang 7",
    price: 5000000,
    priceOriginal: 7812500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Sertifikat%20Kompetensi%20Kerja%20(SKK)%20Jenjang%207!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Kompetensi Kerja (SKK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "Sertifikat Kompetensi Kerja (SKK) Jenjang 8-9",
    price: 6000000,
    priceOriginal: 9375000,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Sertifikat%20Kompetensi%20Kerja%20(SKK)%20Jenjang%208-9!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Kompetensi Kerja (SKK)", status: true },
      { feature: "Kartu Tanda Anggota (KTA)", status: true }
    ]
  },
  {
    type: "ISO 9001 Terakreditasi IAS/IAF",
    price: 9500000,
    priceOriginal: 14843750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20ISO%209001%20Terakreditasi%20IAS/IAF!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat ISO 9001 Terakreditasi IAS/IAF", status: true }
    ]
  },
  {
    type: "ISO 45001 Terakreditasi IAS/IAF",
    price: 12500000,
    priceOriginal: 19531250,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20ISO%2045001%20Terakreditasi%20IAS/IAF!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat ISO 45001 Terakreditasi IAS/IAF", status: true }
    ]
  },
  {
    type: "ISO 37001 Smap Akreditasi KAN",
    price: 45000000,
    priceOriginal: 70312500,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20ISO%2037001%20Smap%20Akreditasi%20KAN!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat ISO 37001 Smap Akreditasi KAN", status: true }
    ]
  },
  {
    type: "ISO 37001 Smap Akreditasi IAS/IAF",
    price: 19500000,
    priceOriginal: 30468750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20ISO%2037001%20Smap%20Akreditasi%20IAS/IAF!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat ISO 37001 Smap Akreditasi IAS/IAF", status: true }
    ]
  },
  {
    type: "Audit Barcode Untuk Izin SBU Skala Menengah dan Besar",
    price: 17500000,
    priceOriginal: 27343750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Audit%20Barcode%20Untuk%20Izin%20SBU!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Audit Barcode", status: true }
    ]
  },
  {
    type: "Sistem Manajemen Keselamatan Dan Kesehatan Kerja (SMK3)",
    price: 27500000,
    priceOriginal: 42968750,
    link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Sistem%20Manajemen%20Keselamatan%20Dan%20Kesehatan%20Kerja%20(SMK3)!",
    discount: 36,
    features: [
      { feature: "Free Konsultasi 24jam", status: true },
      { feature: "Sertifikat Sistem Manajemen Keselamatan Dan Kesehatan Kerja (SMK3)", status: true }
    ]
  }
];
