import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Sidebar } from "@/components/sidebar";
import { BackgroundImage } from "@/components/background-image";
import { SidebarProvider } from "./contexts/sidebar-context";
import { Header } from "@/components/header";
import { Toaster } from "sonner";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import ProtectedRoutes from "@/components/protected-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CMS - Content Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider enableSystem={true} attribute="class">
          <ProtectedRoutes>
              <SidebarProvider>
                <BackgroundImage />

                {/* Main Layout Container */}
                <div className="w-full max-h-screen h-screen flex overflow-hidden">
                  <Sidebar />

                  {/* Right Side: Header + Content */}
                  <div className="flex-1 flex flex-col min-w-0 ">
                    <Header />

                    {/* Content Area */}
                    <main className="flex-1 overflow-hidden">
                      {children}
                    </main>
                    <Toaster position="top-center" richColors />
                  </div>
                </div>
              </SidebarProvider>

          </ProtectedRoutes>
        </ThemeProvider>
      </body>
    </html>
  );
}